# Generated by Django 4.0.6 on 2022-08-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='noteimages')),
            ],
        ),
    ]
